"""Generate operation references and publish an immutable workflow bundle."""

import argparse
import json
from pathlib import Path
from tempfile import TemporaryDirectory

from .application import create_runtime
from .config import McpConfig
from .skills import SkillCatalog


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workspace", type=Path, default=Path.cwd())
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--bundle", type=Path)
    args = parser.parse_args()
    workspace = args.workspace.resolve()
    with TemporaryDirectory(prefix="sagasmith-contract-") as temporary:
        home = Path(temporary)
        runtime = create_runtime(
            McpConfig(
                home=home,
                database_url=None,
                chroma_url=None,
                chroma_path_override=None,
                dnd_skills_dir=home / "absent",
                modulegen_skills_dir=home / "absent-modulegen",
                auto_seed_rules=False,
            )
        )
        try:
            contract = runtime.contract()
        finally:
            runtime.close()
    lines = [
        "# Generated application operation contract",
        "",
        "Generated by `python -m sagasmith_dnd_runtime.publish`; do not edit by hand.",
        "",
        "Identity is supplied by the authenticated Host. Keep the original request and",
        "idempotency key when recovering an unknown dispatch. Never retry with a new key.",
        "",
        "| Operation | Phases | Revision fields | Idempotent |",
        "| --- | --- | --- | --- |",
    ]
    for row in contract:
        lines.append(
            f"| `{row['id']}` | {', '.join(row['phases'])} | "
            f"{', '.join(row['revision_fields']) or '—'} | {row['idempotent']} |"
        )
    generated = {
        "generated-operations.json": json.dumps(
            contract, ensure_ascii=False, indent=2, sort_keys=True
        ) + "\n",
        "generated-operations.md": "\n".join(lines) + "\n",
    }
    for name, text in generated.items():
        path = workspace / "skills/full/references" / name
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                raise SystemExit(f"generated operation reference is stale: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    if args.bundle:
        catalog = SkillCatalog(
            dnd_root=workspace / "skills",
            modulegen_root=workspace / "skills/dnd-module-generator",
        )
        print(catalog.publish(args.bundle))


if __name__ == "__main__":
    main()
