"""Stable identifiers for source-bound standard spell mechanics."""

STANDARD_2014_CONTENT_PACK_ID = "dnd5e.content.standard2014"
STANDARD_2014_CONTENT_PACK_VERSION = "1.0.0"

CORE_BLADE_WARD_MECHANIC_ID = "dnd5e.core.spell.blade_ward"
CORE_BLADE_WARD_SPELL_ID = f"{STANDARD_2014_CONTENT_PACK_ID}.spell.blade-ward"
CORE_FLY_MECHANIC_ID = "dnd5e.core.spell.fly"
CORE_FLY_SPELL_ID = "dnd5e.content.srd2014.spell.fly"
CORE_2024_FLY_SPELL_ID = "dnd5e.content.srd2024.spell.fly"
CORE_FLY_SPELL_IDS = frozenset({CORE_FLY_SPELL_ID, CORE_2024_FLY_SPELL_ID})
CORE_INVISIBILITY_MECHANIC_ID = "dnd5e.core.spell.invisibility"
CORE_INVISIBILITY_SPELL_ID = "dnd5e.content.srd2014.spell.invisibility"
CORE_2024_INVISIBILITY_SPELL_ID = "dnd5e.content.srd2024.spell.invisibility"
CORE_INVISIBILITY_SPELL_IDS = frozenset(
    {CORE_INVISIBILITY_SPELL_ID, CORE_2024_INVISIBILITY_SPELL_ID}
)
CORE_HYPNOTIC_PATTERN_MECHANIC_ID = "dnd5e.core.spell.hypnotic_pattern"
CORE_HYPNOTIC_PATTERN_SPELL_ID = "dnd5e.content.srd2014.spell.hypnotic-pattern"
CORE_2024_HYPNOTIC_PATTERN_SPELL_ID = (
    "dnd5e.content.srd2024.spell.hypnotic-pattern"
)
CORE_HYPNOTIC_PATTERN_SPELL_IDS = frozenset(
    {CORE_HYPNOTIC_PATTERN_SPELL_ID, CORE_2024_HYPNOTIC_PATTERN_SPELL_ID}
)
CORE_WITCH_BOLT_MECHANIC_ID = "dnd5e.core.spell.witch_bolt"
CORE_WITCH_BOLT_SPELL_ID = f"{STANDARD_2014_CONTENT_PACK_ID}.spell.witch-bolt"

__all__ = [
    "CORE_BLADE_WARD_MECHANIC_ID",
    "CORE_BLADE_WARD_SPELL_ID",
    "CORE_2024_FLY_SPELL_ID",
    "CORE_FLY_MECHANIC_ID",
    "CORE_FLY_SPELL_ID",
    "CORE_FLY_SPELL_IDS",
    "CORE_2024_INVISIBILITY_SPELL_ID",
    "CORE_INVISIBILITY_MECHANIC_ID",
    "CORE_INVISIBILITY_SPELL_ID",
    "CORE_INVISIBILITY_SPELL_IDS",
    "CORE_2024_HYPNOTIC_PATTERN_SPELL_ID",
    "CORE_HYPNOTIC_PATTERN_MECHANIC_ID",
    "CORE_HYPNOTIC_PATTERN_SPELL_ID",
    "CORE_HYPNOTIC_PATTERN_SPELL_IDS",
    "CORE_WITCH_BOLT_MECHANIC_ID",
    "CORE_WITCH_BOLT_SPELL_ID",
    "STANDARD_2014_CONTENT_PACK_ID",
    "STANDARD_2014_CONTENT_PACK_VERSION",
]
